import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home, ArrowLeft, Sparkles, MousePointer2, ChevronRight, RotateCcw, Check, BookOpen, Trophy} from 'lucide-react';
import './styles.css';
import {gameLevels} from './gameData';

const games = [
 ['笔画小侦探','stroke','识字入门','找出正确笔画顺序','笔画'],['偏旁配对','radical','结构认知','把偏旁送回正确的汉字','结构'],['拼音小火车','pinyin','字音训练','点击正确的拼音','字音'],['成语补一补','idiom','成语乐园','补上成语中缺少的字','成语'],['诗句接龙','poem','诗词天地','接上下一句诗','诗词'],
 ['同音字碰碰车','homophone','字音训练','找出读音相同的字','字音'],['反义词大作战','opposite','词语王国','选择意思相反的词','词语'],['量词小管家','measure','词语王国','给名词配上合适量词','词语'],['字谜灯会','riddle','趣味识字','猜猜灯谜的答案','趣味'],['部首寻宝','radical2','结构认知','点击含有目标部首的字','结构'],
 ['笔顺跟我写','order','识字入门','按顺序点击笔画','笔画'],['多音字剧场','polyphone','字音训练','选出句中正确读音','字音'],['成语连连看','idiom2','成语乐园','配对成语和意思','成语'],['古诗填空','poem2','诗词天地','点击诗句中的空缺字','诗词'],['近义词花园','similar','词语王国','选择意思相近的词','词语'],
 ['数字汉字屋','number','趣味识字','找出数字对应的汉字','趣味'],['颜色猜字','color','趣味识字','点击描述颜色的汉字','趣味'],['动物字典','animal','百科识字','找出动物名称','百科'],['食物字典','food','百科识字','找出食物名称','百科'],['天气小达人','weather','百科识字','选择对应天气的字','百科'],
 ['汉字找不同','different','识字入门','找出唯一不同的字','笔画'],['字形记忆','memory','识字入门','记住并找回刚才的字','趣味'],['汉字拼图','puzzle','结构认知','拼出完整汉字','结构'],['成语大转盘','idiom3','成语乐园','转出并补全成语','成语'],['诗人小助手','poet','诗词天地','选择诗句作者','诗词'],
 ['声调小达人','tone','字音训练','点击正确声调','字音'],['汉字分类站','classify','词语王国','把字归入正确类别','词语'],['一字开花','flower','词语王国','选择能组成词语的字','词语'],['字宝宝回家','home','趣味识字','把字放回词语中','趣味'],['汉字大冒险','adventure','综合挑战','完成汉字小挑战','综合']
].map((g,i)=>({id:i+1,title:g[0],slug:g[1],category:g[2],desc:g[3],tag:g[4]}));

const palettes=['pink','lavender','blue','peach','mint'];
const sets=[
 ['春','夏','秋','冬','风'],['日','月','山','水','木'],['天','地','人','和','心'],['花','鸟','鱼','虫','云'],['大','小','多','少','高'],
 ['明','星','清','风','白'],['上','下','左','右','中'],['红','黄','蓝','绿','紫'],['猫','狗','兔','鹿','牛'],['米','饭','茶','果','糖']
];
function Header({onHome}){return <header><button className="iconBtn" onClick={onHome} aria-label="返回首页"><Home size={20}/></button><div className="brand"><img src="/yangge.png"/><div><b>杨哥快乐屋</b><span>汉字小游戏大全</span></div></div><div className="headerNote"><Sparkles size={17}/> 轻松学汉字 · 快乐每一关</div></header>}
function HomePage({open}){const [filter,setFilter]=useState('全部');const cats=['全部','识字入门','结构认知','字音训练','成语乐园','诗词天地','词语王国','趣味识字','百科识字','综合挑战'];const list=filter==='全部'?games:games.filter(g=>g.category===filter);return <><Header onHome={()=>{}}/><main className="home"><section className="hero"><div><p className="eyebrow">WELCOME · 选择你的汉字冒险</p><h1>今天，也和汉字玩一会儿。</h1><p className="heroText">30 个轻巧有趣的点击小游戏，每个游戏 5 关。没有倒计时，没有惩罚，慢慢玩，稳稳学。</p><button className="primary" onClick={()=>open(games[0])}>开始第一局 <ChevronRight size={18}/></button></div><div className="heroArt"><div className="sun"></div><img src="/yangge.png"/><div className="artLabel">杨哥的快乐汉字屋</div></div></section><section className="library"><div className="sectionHead"><div><p className="eyebrow">GAME LIBRARY</p><h2>30 个小游戏</h2></div><div className="count"><Trophy size={16}/> 已收录 30 / 30</div></div><div className="filters">{cats.map(c=><button className={filter===c?'active':''} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div><div className="grid">{list.map((g,i)=><article className={`gameCard ${palettes[g.id%5]}`} key={g.id} onClick={()=>open(g)}><div className="cardNo">{String(g.id).padStart(2,'0')}</div><div className="cardIcon">{sets[g.id%sets.length][g.id%5]}</div><div className="cardBody"><span className="tag">{g.tag}</span><h3>{g.title}</h3><p>{g.desc}</p><div className="playLine">进入游戏 <ChevronRight size={16}/></div></div></article>)}</div></section></main></>}
function GamePage({game,onHome}){const [level,setLevel]=useState(1);const [selected,setSelected]=useState(null);const [message,setMessage]=useState('');const [done,setDone]=useState(false);const data=gameLevels[game.slug][level-1];function choose(x){if(selected===data.answer)return;if(x!==data.answer){setSelected(x);setMessage('还差一点，留在本关再试一次。');return}setSelected(x);setMessage('答对了！');setTimeout(()=>{if(level===5)setDone(true);else{setLevel(v=>v+1);setSelected(null);setMessage('')}},650)}return <><Header onHome={onHome}/><main className="gamePage"><button className="back" onClick={onHome}><ArrowLeft size={17}/> 游戏大厅</button><div className="gameTop"><div><p className="eyebrow">{game.category} · 第 {level} 关</p><h1>{game.title}</h1><p>{game.desc}。答对才会进入下一关。</p></div><div className="progress">{[1,2,3,4,5].map(n=><span className={n<level||done?'filled':''} key={n}>{n<level||done?<Check size={14}/>:n}</span>)}</div></div><section className="playPanel">{done?<div className="complete"><div className="completeIcon"><Trophy size={42}/></div><p className="eyebrow">太棒了</p><h2>五关全部完成！</h2><p>你已经完成「{game.title}」的全部专属题目。</p><div className="actions"><button className="primary" onClick={()=>{setLevel(1);setDone(false);setSelected(null);setMessage('')}}><RotateCcw size={17}/> 再玩一次</button><button className="secondary" onClick={onHome}>回到大厅</button></div></div>:<><div className={`prompt mode-${game.id%6}`}><span className="promptLabel">第 {level} 题 · {game.title}</span><div className="questionText">{data.question}</div></div><div className="options">{data.options.map((x,i)=><button className={`option ${selected===x?(x===data.answer?'correct':'wrong'):''}`} onClick={()=>choose(x)} key={`${x}-${i}`}><span>{x}</span><small>{String.fromCharCode(65+i)}</small></button>)}</div><div className={`feedback ${selected?(selected===data.answer?'ok':'try'):''}`}>{message||<><MousePointer2 size={17}/> 点击一个答案 · 答错可继续尝试</>}</div></>}</section></main></>}
function setUrl(game){location.hash=game?`/game/${game.slug}`:'/'}
function App(){const findGame=()=>games.find(g=>location.hash===`#/game/${g.slug}`)||null;const [game,setGame]=useState(findGame);React.useEffect(()=>{const f=()=>setGame(findGame());addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);const open=g=>{setGame(g);setUrl(g)};const home=()=>{setGame(null);setUrl(null)};return game?<GamePage game={game} onHome={home}/>:<HomePage open={open}/>};
createRoot(document.getElementById('root')).render(<App/>);
